///////////////////////////////////////////////////////////
//  Alfil.cs
//  Implementation of the Class Alfil
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:07
//  Original author: vguar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Alfil : Ficha {

	private Color Colour;

    public Alfil(Color _Colour, string _Nombre) : base(_Nombre)
    {
		Colour = _Colour;
    }

    ~Alfil(){

	}

	public override void Atacar(Tablero Ataque)
	{
		Diagonal1(Ataque);
		Diagonal2(Ataque);
		Diagonal3(Ataque);
		Diagonal4(Ataque);
	}

}//end Alfil