///////////////////////////////////////////////////////////
//  Alfil.cs
//  Implementation of the Class Alfil
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:07
//  Original author: vguar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

public enum ColorAlfil : int
{

	BLANCO,
	NEGRO

}//end ColorAlfil

public class Alfil : Ficha {

	private ColorAlfil Color;

	public Alfil(){

	}

	~Alfil(){

	}

	public override void Atacar(Tablero Ataque)
	{
		Diagonal1(Ataque);
		Diagonal2(Ataque);
		Diagonal3(Ataque);
		Diagonal4(Ataque);
	}

}//end Alfil