///////////////////////////////////////////////////////////
//  Casilla.cs
//  Implementation of the Class Casilla
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:07
//  Original author: vguar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Casilla {

	private bool Atacada;
	private ushort Columna;
	private ushort Fila;
	private bool Ocupada;
	public Ficha m_Ficha;

	public Casilla(){

	}

	~Casilla(){

	}

    public bool Ocupar()
    {
        if (!Ocupada && !(m_Ficha is Torre)) //el dynamic_cast en C#
            return false; //si estoy ocupada, no se puede posicionar una ficha
		
        Ocupada = true; //la casilla estaba desocupada, entonces la ocupo
        return true; //la pude ocupar
    }

}//end Casilla