///////////////////////////////////////////////////////////
//  Rey.cs
//  Implementation of the Class Rey
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:07
//  Original author: vguar
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


public class Rey : Ficha {

	public Rey(){

	}

	~Rey(){

	}

	public override void Atacar(Tablero Ataque){
		uint i = Pos.Columna;
		uint j = Pos.Fila;

		if (i + 1 < 8)
			Ataque.Matriz[i + 1, j].SetAtacada(true);

		if (i - 1 >= 0)
			Ataque.Matriz[i - 1, j].SetAtacada(true);

		if (j + 1 < 8)
        {
			Ataque.Matriz[i, j + 1].SetAtacada(true);
			if (i + 1 < 8)
				Ataque.Matriz[i + 1, j + 1].SetAtacada(true);
			if (i - 1 >= 0)
				Ataque.Matriz[i - 1, j - 1].SetAtacada(true);
		}

		if (j - 1 >= 0)
        {
			Ataque.Matriz[i, j - 1].SetAtacada(true);
			if (i + 1 < 8)
				Ataque.Matriz[i + 1, j - 1].SetAtacada(true);
			if (i - 1 >= 0)
				Ataque.Matriz[i - 1, j + 1].SetAtacada(true);
		}
	}

}//end Rey