///////////////////////////////////////////////////////////
//  Rey.cs
//  Implementation of the Class Rey
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:07
//  Original author: vguar
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


public class Rey : Ficha {

	public Rey(){

	}

	~Rey(){

	}

	public override void Atacar(Tablero Ataque){
		ushort i = Posicion.GetColumna();
		ushort j = Posicion.GetFila();

		if (i + 1 < 8)
			Ataque[i + 1, j].Atacada = true;

		if (i -1 >=0)
			Ataque[i - 1, j].Atacada = true;

		if (j + 1 < 8)
        {
			Ataque[i, j + 1].Atacada = true;
			if (i + 1 < 8)
				Ataque[i + 1, j + 1].Atacada = true;
			if (i - 1 >= 0)
				Ataque[i - 1, j - 1].Atacada = true;
		}

		if (j - 1 >= 0)
        {
			Ataque[i, j - 1].Atacada = true;
			if (i + 1 < 8)
				Ataque[i + 1, j - 1].Atacada = tru;
			if (i - 1 >= 0)
				Ataque[i - 1, j + 1].Atacada = true;
		}
	}

}//end Rey