///////////////////////////////////////////////////////////
//  Tablero.cs
//  Implementation of the Class Tablero
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:08
//  Original author: vguar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Tablero {

	private static uint ContSoluciones;
	private ushort ID;
	public Casilla m_Casilla;

	//public Casilla[,] Matriz;
		
	//LinkedList<Casilla> ListaPosiciones = new LinkedList<Casilla>();

	/*public void InicializarListaPos()
    {
		for(uint i =0; i < 8; i++)
        {
			
        }
    }*/

	public Tablero(){

	}

	~Tablero(){

	}

	public Tablero Espejar(){

		return null;
	}

	public void FiltrarFatales(){

	}

	public void Imprimir(){

	}

	public void Limpiar(){

	}

	/// 
	/// <param name="Ficha"></param>
	public void Pintar(Ficha Ficha){

	}

    /*posiciónar(Ficha Ficha, lista posiciónes, Tablero) → void
	FIcha. posición = Elegir random posición de lista posiciónes
	Si Tablero.Ocupar(posición) = false
	posiciónar(Ficha Ficha, lista posiciónes, Tablero)
	Tablero.Atacar(ficha)*/

    /// 
    /// <param name="Ficha"></param>
    /// <param name="ListaPos"></param>
    public void Posicionar(Ficha Ficha)
    {
        //Variables locales
        Random r = new Random();
        Casilla newPos;

        newPos.SetFila(Convert.ToUInt16(r.Next(0, 8));
        newPos.SetColumna(Convert.ToUInt16(r.Next(0, 8));

        if (!newPos.Ocupar())
            Posicionar(Ficha);
    }

    public Tablero Rotar(){

		return null;
	}

}//end Tablero