///////////////////////////////////////////////////////////
//  Torre.cs
//  Implementation of the Class Torre
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:08
//  Original author: vguar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Torre : Ficha {

	public Torre(){

	}

	~Torre(){

	}

	public override void Atacar(){

	}

}//end Torre