///////////////////////////////////////////////////////////
//  Torre.cs
//  Implementation of the Class Torre
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:08
//  Original author: vguar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Torre : Ficha {

	public Torre(string _Nombre): base(_Nombre)
	{

	}

	~Torre(){

	}

	public override void Atacar(Tablero Ataque, bool Fatal)
	{
		Horizontal1(Ataque, Fatal);
		Horizontal2(Ataque, Fatal);
		Vertical1(Ataque, Fatal);
		Vertical2(Ataque, Fatal);
	}

}//end Torre