///////////////////////////////////////////////////////////
//  Alfil.cs
//  Implementation of the Class Alfil
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:07
//  Original author: vguar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Alfil : Ficha {

	private ColorAlfil Color;

	public Alfil(){

	}

	~Alfil(){

	}

	public override void Atacar(){

	}

}//end Alfil