///////////////////////////////////////////////////////////
//  Caballo.cs
//  Implementation of the Class Caballo
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:07
//  Original author: vguar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Caballo : Ficha {

	public Caballo(){

	}

	~Caballo(){

	}

	public override void Atacar(){

	}

}//end Caballo