///////////////////////////////////////////////////////////
//  ColorAlfil.cs
//  Implementation of the Enumeration ColorAlfil
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:07
//  Original author: vguar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum ColorAlfil : int {

	BLANCO,
	NEGRO

}//end ColorAlfil