///////////////////////////////////////////////////////////
//  Ficha.cs
//  Implementation of the Class Ficha
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:07
//  Original author: vguar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ficha {

	private string Nombre;
	private Casilla Posicion;
	public Tablero m_Tablero;

	public Ficha(){

	}

	~Ficha(){

	}

	public abstract void Atacar();

}//end Ficha