///////////////////////////////////////////////////////////
//  Tablero.cs
//  Implementation of the Class Tablero
//  Generated by Enterprise Architect
//  Created on:      06-oct.-2021 08:09:08
//  Original author: vguar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Tablero {

	private static uint ContSoluciones;
	private ushort ID;
	public Casilla m_Casilla;

	public Tablero(){

	}

	~Tablero(){

	}

	public Tablero Espejar(){

		return null;
	}

	public void FiltrarFatales(){

	}

	public void Imprimir(){

	}

	public void Limpiar(){

	}

	/// 
	/// <param name="Ficha"></param>
	public void Pintar(Ficha Ficha){

	}

	/// 
	/// <param name="Ficha"></param>
	/// <param name="ListaPos"></param>
	public void Posicionar(Ficha Ficha, uint[] ListaPos){

	}

	public Tablero Rotar(){

		return null;
	}

}//end Tablero